import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <ul>
          <li className = {styles.link}><Link href = "/products">Products(ISR)</Link></li>
          <li className = {styles.link}><Link href = "/about">Static</Link></li>
          <li className = {styles.link}><Link href = "/server-side">Server-side Example</Link> </li>
          <li className = {styles.link}><Link href = "/ssg">SSG</Link> </li>
        </ul>
      </body>
    </div>
  )
}
