import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import wallpaper from '../public/Luffy.png'

// const myLoader = ({ src, width, quality }) => {
//   return `https://example.com/${src}?w=${width}&q=${quality || 75}`
// }

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={wallpaper} alt = "Luffy"/>
      <Image
      // loader = {myLoader} 
      src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/527f2c83-b33d-43f4-8aa8-a95372ee139e/ddsdvme-5ca9434c-99e6-4501-8216-108503c270c6.jpg/v1/fill/w_1316,h_607,q_70,strp/one_piece_chapter_974_luffy_kid_law_final_trio_by_amanomoon_ddsdvme-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTQ2IiwicGF0aCI6IlwvZlwvNTI3ZjJjODMtYjMzZC00M2Y0LThhYTgtYTk1MzcyZWUxMzllXC9kZHNkdm1lLTVjYTk0MzRjLTk5ZTYtNDUwMS04MjE2LTEwODUwM2MyNzBjNi5qcGciLCJ3aWR0aCI6Ijw9MjA0OCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.lEXUUXbm0yvxf_AN_JM2ij2_SwG_UYdmCj_zY24ur24" alt="LuffyKidLaw" width={500} height={500}/>
      <body>
        <ul>
          <li className = {styles.link}><Link href = "/products">Products(ISR)</Link></li>
          <li className = {styles.link}><Link href = "/about">Static</Link></li>
          <li className = {styles.link}><Link href = "/server-side">Server-side Example</Link> </li>
          <li className = {styles.link}><Link href = "/ssg">SSG</Link> </li>
        </ul>
      </body>
    </div>
  )
}
