name: Build and deploy Node.js app to Azure Web App - nodeJsTesting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: node-app
          path: .

  deploy:      
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure login 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS}}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nodeJsTesting'
          slot-name: 'Production'